blog/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2020/3/24 18:09
# @Author  : Sinclair
# @Email   : 1178211058@qq.com
# @File    : urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("detail/<int:pk>", views.detail, name="detail"),
    path("comment/<int:pk>", views.comment, name="comment"),
    path("add", views.add, name="add"),
]

myblog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from user import views

urlpatterns = [
    path('', views.index, name="index"),
    url("^user/", include("user.urls")),
    url("^blog/", include("blog.urls")),
    url("^notes/", include("notes.urls")),
    path('admin/', admin.site.urls),
]

notes/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2020/3/24 18:09
# @Author  : Sinclair
# @Email   : 1178211058@qq.com
# @File    : urls.py
from django.urls import path
from . import views

app_name = "notes"
urlpatterns = [
    path("mynotes", views.mynotes, name="mynotes"),
    path("add", views.add, name="add"),
    path("modify", views.modify, name="modify"),
    path("del/<str:pk>", views.delete, name="delete"),
]

notes/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Notes(models.Model):
    n_create_time = models.DateTimeField(blank=True, null=True)
    n_content = models.CharField(max_length=255, blank=True, null=True)
    n_is_done = models.IntegerField(blank=True, null=True, default=0)

    class Meta:
        managed = True
        db_table = 't_notes'

notes/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from notes.models import Notes
from datetime import datetime
from utils.mydecorators import confirm_login


# Create your views here.
@confirm_login
def mynotes(request):
    notes = Notes.objects.all()
    completed = Notes.objects.filter(n_is_done=1)
    no_completed = Notes.objects.filter(n_is_done=0)
    return render(request, 'notes/notes.html', {"notes": notes, "completed": completed, "no_completed": no_completed})


@csrf_exempt
def add(request):
    params = request.POST.dict()
    content = params['content']
    c_time = datetime.now()
    note = Notes(n_create_time=c_time, n_content=content)
    note.save()
    data = {"status": 1}
    return JsonResponse(data=data)


@csrf_exempt
def modify(request):
    params = request.POST.dict()
    pk = params['pk']
    is_done = params['is_done']
    note = Notes.objects.filter(pk=pk)
    note = note[0]
    if is_done == "true":
        note.n_is_done = 1
    else:
        note.n_is_done = 0
    note.save()
    data = {"status": 1}
    return JsonResponse(data=data)


def delete(request, pk):
    pk=int(pk)
    Notes.objects.filter(pk=pk).delete()
    # note = Notes.objects.filter(pk=pk)
    # note = note[0]
    # note.delete()
    data = {"status": 1}
    return JsonResponse(data=data)

templates/notes/notes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的便签</title>
    <script src="/static/js/jquery-3.2.1.min.js"></script>
</head>
<body>
<input type="text" id="mynote">
<input type="button" id="add_notes" value="添加便笺">

<ul>
    {% for note in notes %}
        <li class="note_item">
            <input {% if note.n_is_done == 1 %}
                checked="checked"
            {% endif %} id="{{ note.pk }}" class="choose" type="checkbox">{{ note.n_content }} <input class="del" type="button"
                                                                                                      value="删除">
        </li>
    {% endfor %}
    {{ no_completed.count }}未完成，{{ completed.count }}已完成，共{{ notes.count }}个
</ul>
<script>
    $(function () {

        $(".note_item .choose").click(function () {

            console.log($(this).prop("checked"), $(this).attr("id"))
            let is_done = $(this).prop("checked")
            let pk = $(this).attr("id")
            $.ajax({
                url: "{% url 'notes:modify' %}",
                method: "post",
                data: {"pk": pk, "is_done": is_done},
                success: function (data) {
                    {#alert(data.status)#}
                    console.log(data.status)
                    if (data.status == 1) {
                        window.location.reload()
                    }
                }
            })
        })

        $(".note_item .del").click(function () {

            let pk = $(this).prev().attr("id")
            console.log(pk)
            $.ajax({
                url: "/notes/del/"+pk,
                method: "get",
                success: function (data) {
                    console.log(data.status)
                    if (data.status == 1) {
                        window.location.reload()
                    }
                }
            })
        })

        $("#add_notes").click(function () {
            let content = $("#mynote").val()
            console.log(content)
            $.ajax({
                url: "{% url 'notes:add' %}",
                method: "post",
                data: {"content": content},
                success: function (data) {
                    {#alert(data.status)#}
                    console.log(data.status)
                    if (data.status == 1) {
                        window.location.reload()
                    }
                }
            })
        })

    })
</script>
</body>
</html>